
export const REDUX_SAVE_ALL_HADITH="REDUX_SAVE_ALL_HADITH"
export const REDUX_RELOAD_HOME = "REDUX_RELOAD_HOME"
export const REDUX_SAVE_HADITH_BY_CATEGORY = "REDUX_SAVE_HADITH_BY_CATEGORY"
export const REDUX_SAVE_HADITH_BY_CATEGORY_ID = "REDUX_SAVE_HADITH_BY_CATEGORY_ID"